/*
===============================================================================
 Name        : Total_Init.c
 Author      : Guillermo Ariel Muena
 E-Mail		 : guillermuena@est.utn.frba.utn.edu.ar
 Version     : v0.01
 Copyright   : Free, as long as you give me some credit. Make sure to tell me
 	 	 	   of any change or improvement you make.
 Description : Function of initialization via conditional compiling. Easy to use.
   	   	   	   The only thing you have to do to enable a pin properly is: enter
   	   	   	   Total_Init_Config.h and change the values of the pin you want to
   	   	   	   configure.

   	   	   	   WARNING: Pay close attention to which pin you are configuring and
   	   	   	   make sure that you are not enabling more than one function of that
   	   	   	   pin.

   	   	   	   RECOMENDATION: Look in Total_Init.h before configuring any pin and
   	   	   	   make sure that you are not using more than one function of that
   	   	   	   particular pin

   	   	   	   Happy programming :D
===============================================================================
*/

#if defined (__USE_LPCOPEN)
#if defined(NO_BOARD_LIB)
#include "chip.h"
#else
#include "board.h"
#endif
#endif

#include <cr_section_macros.h>


#include "Total_Init.h"
#include "Total_Init_Config.h"

#define OD 	4
#define PP 	5

void Init_GPIO_PINS(void){
#if	ENABLE_GPIO
	#if	ENABLE_GPIO_PORT0

		#if ENABLE_GPIO_PORT_0_PIN_0
			#if DIRECTION_GPIO_PORT_0_PIN_0 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_0, GPIO_TYPE_GPIO_PORT_0_PIN_0, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_0, DIRECTION_GPIO_PORT_0_PIN_0);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_0, GPIO_TYPE_GPIO_PORT_0_PIN_0, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_0 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_0);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_0);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_0, DIRECTION_GPIO_PORT_0_PIN_0);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_21
			#if DIRECTION_GPIO_PORT_0_PIN_21 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_21, GPIO_TYPE_GPIO_PORT_0_PIN_21, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_21, DIRECTION_GPIO_PORT_0_PIN_21);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_21, GPIO_TYPE_GPIO_PORT_0_PIN_21, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_21 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_21);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_21);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_21, DIRECTION_GPIO_PORT_0_PIN_21);
				#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_2
			#if DIRECTION_GPIO_PORT_0_PIN_2 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_2, GPIO_TYPE_GPIO_PORT_0_PIN_2, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_2, DIRECTION_GPIO_PORT_0_PIN_2);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_2, GPIO_TYPE_GPIO_PORT_0_PIN_2, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_2 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_2);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_2);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_2, DIRECTION_GPIO_PORT_0_PIN_2);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_3
			#if DIRECTION_GPIO_PORT_0_PIN_3 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_3, GPIO_TYPE_GPIO_PORT_0_PIN_3, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_3, DIRECTION_GPIO_PORT_0_PIN_3);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_3, GPIO_TYPE_GPIO_PORT_0_PIN_3, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_3 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_3);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_3);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_3, DIRECTION_GPIO_PORT_0_PIN_3);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_4
			#if DIRECTION_GPIO_PORT_0_PIN_4 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_4, GPIO_TYPE_GPIO_PORT_0_PIN_4, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_4, DIRECTION_GPIO_PORT_0_PIN_4);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_4, GPIO_TYPE_GPIO_PORT_0_PIN_4, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_4 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_4);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_4);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_4, DIRECTION_GPIO_PORT_0_PIN_4);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_5
			#if DIRECTION_GPIO_PORT_0_PIN_5 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_5, GPIO_TYPE_GPIO_PORT_0_PIN_5, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_5, DIRECTION_GPIO_PORT_0_PIN_5);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_5, GPIO_TYPE_GPIO_PORT_0_PIN_5, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_5 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_5);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_5);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_5, DIRECTION_GPIO_PORT_0_PIN_5);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_6
			#if DIRECTION_GPIO_PORT_0_PIN_6 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_6, GPIO_TYPE_GPIO_PORT_0_PIN_6, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_6, DIRECTION_GPIO_PORT_0_PIN_6);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_6, GPIO_TYPE_GPIO_PORT_0_PIN_6, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_6 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_6);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_6);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_6, DIRECTION_GPIO_PORT_0_PIN_6);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_7
			#if DIRECTION_GPIO_PORT_0_PIN_7 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_7, GPIO_TYPE_GPIO_PORT_0_PIN_7, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_7, DIRECTION_GPIO_PORT_0_PIN_7);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_7, GPIO_TYPE_GPIO_PORT_0_PIN_7, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_7 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_7);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_7);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_7, DIRECTION_GPIO_PORT_0_PIN_7);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_8
			#if DIRECTION_GPIO_PORT_0_PIN_8 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_8, GPIO_TYPE_GPIO_PORT_0_PIN_8, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_8, DIRECTION_GPIO_PORT_0_PIN_8);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_8, GPIO_TYPE_GPIO_PORT_0_PIN_8, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_8 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_8);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_8);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_8, DIRECTION_GPIO_PORT_0_PIN_8);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_9
			#if DIRECTION_GPIO_PORT_0_PIN_9 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_9, GPIO_TYPE_GPIO_PORT_0_PIN_9, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_9, DIRECTION_GPIO_PORT_0_PIN_9);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_9, GPIO_TYPE_GPIO_PORT_0_PIN_9, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_9 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_9);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_9);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_9, DIRECTION_GPIO_PORT_0_PIN_9);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_10
			#if DIRECTION_GPIO_PORT_0_PIN_10 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_10, GPIO_TYPE_GPIO_PORT_0_PIN_10, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_10, DIRECTION_GPIO_PORT_0_PIN_10);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_10, GPIO_TYPE_GPIO_PORT_0_PIN_10, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_10 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_10);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_10);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_10, DIRECTION_GPIO_PORT_0_PIN_10);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_11
			#if DIRECTION_GPIO_PORT_0_PIN_11 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_11, GPIO_TYPE_GPIO_PORT_0_PIN_11, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_11, DIRECTION_GPIO_PORT_0_PIN_11);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_11, GPIO_TYPE_GPIO_PORT_0_PIN_11, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_11 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_11);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_11);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_11, DIRECTION_GPIO_PORT_0_PIN_11);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_15
			#if DIRECTION_GPIO_PORT_0_PIN_15 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_15, GPIO_TYPE_GPIO_PORT_0_PIN_15, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_15, DIRECTION_GPIO_PORT_0_PIN_15);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_15, GPIO_TYPE_GPIO_PORT_0_PIN_15, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_15 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_15);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_15);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_15, DIRECTION_GPIO_PORT_0_PIN_15);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_16
			#if DIRECTION_GPIO_PORT_0_PIN_16 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_16, GPIO_TYPE_GPIO_PORT_0_PIN_16, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_16, DIRECTION_GPIO_PORT_0_PIN_16);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_16, GPIO_TYPE_GPIO_PORT_0_PIN_16, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_16 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_16);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_16);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_16, DIRECTION_GPIO_PORT_0_PIN_16);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_17
			#if DIRECTION_GPIO_PORT_0_PIN_17 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_17, GPIO_TYPE_GPIO_PORT_0_PIN_17, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_17, DIRECTION_GPIO_PORT_0_PIN_17);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_17, GPIO_TYPE_GPIO_PORT_0_PIN_17, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_17 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_17);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_17);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_17, DIRECTION_GPIO_PORT_0_PIN_17);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_18
			#if DIRECTION_GPIO_PORT_0_PIN_18 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_18, GPIO_TYPE_GPIO_PORT_0_PIN_18, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_18, DIRECTION_GPIO_PORT_0_PIN_18);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_18, GPIO_TYPE_GPIO_PORT_0_PIN_18, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_18 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_18);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_18);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_18, DIRECTION_GPIO_PORT_0_PIN_18);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_19
			#if DIRECTION_GPIO_PORT_0_PIN_19 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_19, GPIO_TYPE_GPIO_PORT_0_PIN_19, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_19, DIRECTION_GPIO_PORT_0_PIN_19);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_19, GPIO_TYPE_GPIO_PORT_0_PIN_19, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_19 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_19);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_19);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_19, DIRECTION_GPIO_PORT_0_PIN_19);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_20
			#if DIRECTION_GPIO_PORT_0_PIN_20 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_20, GPIO_TYPE_GPIO_PORT_0_PIN_20, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_20, DIRECTION_GPIO_PORT_0_PIN_20);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_20, GPIO_TYPE_GPIO_PORT_0_PIN_20, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_20 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_20);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_20);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_20, DIRECTION_GPIO_PORT_0_PIN_20);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_21
			#if DIRECTION_GPIO_PORT_0_PIN_21 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_21, GPIO_TYPE_GPIO_PORT_0_PIN_21, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_21, DIRECTION_GPIO_PORT_0_PIN_21);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_21, GPIO_TYPE_GPIO_PORT_0_PIN_21, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_21 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_21);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_21);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_21, DIRECTION_GPIO_PORT_0_PIN_21);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_22
			#if DIRECTION_GPIO_PORT_0_PIN_22 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_22, GPIO_TYPE_GPIO_PORT_0_PIN_22, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_22, DIRECTION_GPIO_PORT_0_PIN_22);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_22, GPIO_TYPE_GPIO_PORT_0_PIN_22, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_22 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_22);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_22);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_22, DIRECTION_GPIO_PORT_0_PIN_22);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_23
			#if DIRECTION_GPIO_PORT_0_PIN_23 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_23, GPIO_TYPE_GPIO_PORT_0_PIN_23, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_23, DIRECTION_GPIO_PORT_0_PIN_23);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_23, GPIO_TYPE_GPIO_PORT_0_PIN_23, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_23 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_23);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_23);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_23, DIRECTION_GPIO_PORT_0_PIN_23);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_24
			#if DIRECTION_GPIO_PORT_0_PIN_24 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_24, GPIO_TYPE_GPIO_PORT_0_PIN_24, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_24, DIRECTION_GPIO_PORT_0_PIN_24);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_24, GPIO_TYPE_GPIO_PORT_0_PIN_24, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_24 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_24);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_24);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_24, DIRECTION_GPIO_PORT_0_PIN_24);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_25
			#if DIRECTION_GPIO_PORT_0_PIN_25 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_25, GPIO_TYPE_GPIO_PORT_0_PIN_25, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_25, DIRECTION_GPIO_PORT_0_PIN_25);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_25, GPIO_TYPE_GPIO_PORT_0_PIN_25, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_25 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_25);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_25);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_25, DIRECTION_GPIO_PORT_0_PIN_25);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_26
			#if DIRECTION_GPIO_PORT_0_PIN_26 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_26, GPIO_TYPE_GPIO_PORT_0_PIN_26, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_26, DIRECTION_GPIO_PORT_0_PIN_26);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_26, GPIO_TYPE_GPIO_PORT_0_PIN_26, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_26 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_26);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_26);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_26, DIRECTION_GPIO_PORT_0_PIN_26);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_27
			#if DIRECTION_GPIO_PORT_0_PIN_27 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_27, GPIO_TYPE_GPIO_PORT_0_PIN_27, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_27, DIRECTION_GPIO_PORT_0_PIN_27);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_27, GPIO_TYPE_GPIO_PORT_0_PIN_27, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_27 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_27);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_27);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_27, DIRECTION_GPIO_PORT_0_PIN_27);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_28
			#if DIRECTION_GPIO_PORT_0_PIN_28 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_28, GPIO_TYPE_GPIO_PORT_0_PIN_28, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_28, DIRECTION_GPIO_PORT_0_PIN_28);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_28, GPIO_TYPE_GPIO_PORT_0_PIN_28, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_28 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_28);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_28);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_28, DIRECTION_GPIO_PORT_0_PIN_28);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_29
			#if DIRECTION_GPIO_PORT_0_PIN_29 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_29, GPIO_TYPE_GPIO_PORT_0_PIN_29, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_29, DIRECTION_GPIO_PORT_0_PIN_29);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_29, GPIO_TYPE_GPIO_PORT_0_PIN_29, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_29 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_29);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_29);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_29, DIRECTION_GPIO_PORT_0_PIN_29);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_0_PIN_30
			#if DIRECTION_GPIO_PORT_0_PIN_30 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_30, GPIO_TYPE_GPIO_PORT_0_PIN_30, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_30, DIRECTION_GPIO_PORT_0_PIN_30);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_0_PIN_30, GPIO_TYPE_GPIO_PORT_0_PIN_30, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_0_PIN_30 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_0_PIN_30);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_0_PIN_30);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_0_PIN_30, DIRECTION_GPIO_PORT_0_PIN_30);
			#endif
		#endif
	#endif

	#if	ENABLE_GPIO_PORT1

		#if ENABLE_GPIO_PORT_1_PIN_0
			#if DIRECTION_GPIO_PORT_1_PIN_0 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_0, GPIO_TYPE_GPIO_PORT_1_PIN_0, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_0, DIRECTION_GPIO_PORT_1_PIN_0);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_0, GPIO_TYPE_GPIO_PORT_1_PIN_0, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_0 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_0);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_0);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_0, DIRECTION_GPIO_PORT_1_PIN_0);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_1
			#if DIRECTION_GPIO_PORT_1_PIN_1 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_1, GPIO_TYPE_GPIO_PORT_1_PIN_1, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_1, DIRECTION_GPIO_PORT_1_PIN_1);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_1, GPIO_TYPE_GPIO_PORT_1_PIN_1, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_1 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_1);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_1);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_1, DIRECTION_GPIO_PORT_1_PIN_1);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_4
			#if DIRECTION_GPIO_PORT_1_PIN_4 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_4, GPIO_TYPE_GPIO_PORT_1_PIN_4, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_4, DIRECTION_GPIO_PORT_1_PIN_4);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_4, GPIO_TYPE_GPIO_PORT_1_PIN_4, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_4 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_4);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_4);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_4, DIRECTION_GPIO_PORT_1_PIN_4);
			#endif
		#endif


		#if ENABLE_GPIO_PORT_1_PIN_8
			#if DIRECTION_GPIO_PORT_1_PIN_8 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_8, GPIO_TYPE_GPIO_PORT_1_PIN_8, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_8, DIRECTION_GPIO_PORT_1_PIN_8);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_8, GPIO_TYPE_GPIO_PORT_1_PIN_8, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_8 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_8);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_8);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_8, DIRECTION_GPIO_PORT_1_PIN_8);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_9
			#if DIRECTION_GPIO_PORT_1_PIN_9 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_9, GPIO_TYPE_GPIO_PORT_1_PIN_9, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_9, DIRECTION_GPIO_PORT_1_PIN_9);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_9, GPIO_TYPE_GPIO_PORT_1_PIN_9, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_9 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_9);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_9);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_9, DIRECTION_GPIO_PORT_1_PIN_9);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_10
			#if DIRECTION_GPIO_PORT_1_PIN_10 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_10, GPIO_TYPE_GPIO_PORT_1_PIN_10, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_10, DIRECTION_GPIO_PORT_1_PIN_10);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_10, GPIO_TYPE_GPIO_PORT_1_PIN_10, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_10 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_10);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_10);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_10, DIRECTION_GPIO_PORT_1_PIN_10);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_14
			#if DIRECTION_GPIO_PORT_1_PIN_14 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_14, GPIO_TYPE_GPIO_PORT_1_PIN_14, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_14, DIRECTION_GPIO_PORT_1_PIN_14);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_14, GPIO_TYPE_GPIO_PORT_1_PIN_14, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_14 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_14);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_14);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_14, DIRECTION_GPIO_PORT_1_PIN_14);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_15
			#if DIRECTION_GPIO_PORT_1_PIN_15 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_15, GPIO_TYPE_GPIO_PORT_1_PIN_15, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_15, DIRECTION_GPIO_PORT_1_PIN_15);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_15, GPIO_TYPE_GPIO_PORT_1_PIN_15, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_15 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_15);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_15);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_15, DIRECTION_GPIO_PORT_1_PIN_15);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_16
			#if DIRECTION_GPIO_PORT_1_PIN_16 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_16, GPIO_TYPE_GPIO_PORT_1_PIN_16, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_16, DIRECTION_GPIO_PORT_1_PIN_16);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_16, GPIO_TYPE_GPIO_PORT_1_PIN_16, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_16 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_16);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_16);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_16, DIRECTION_GPIO_PORT_1_PIN_16);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_17
			#if DIRECTION_GPIO_PORT_1_PIN_17 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_17, GPIO_TYPE_GPIO_PORT_1_PIN_17, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_17, DIRECTION_GPIO_PORT_1_PIN_17);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_17, GPIO_TYPE_GPIO_PORT_1_PIN_17, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_17 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_17);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_17);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_17, DIRECTION_GPIO_PORT_1_PIN_17);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_18
			#if DIRECTION_GPIO_PORT_1_PIN_18 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_18, GPIO_TYPE_GPIO_PORT_1_PIN_18, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_18, DIRECTION_GPIO_PORT_1_PIN_18);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_18, GPIO_TYPE_GPIO_PORT_1_PIN_18, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_18 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_18);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_18);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_18, DIRECTION_GPIO_PORT_1_PIN_18);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_19
			#if DIRECTION_GPIO_PORT_1_PIN_19 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_19, GPIO_TYPE_GPIO_PORT_1_PIN_19, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_19, DIRECTION_GPIO_PORT_1_PIN_19);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_19, GPIO_TYPE_GPIO_PORT_1_PIN_19, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_19 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_19);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_19);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_19, DIRECTION_GPIO_PORT_1_PIN_19);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_20
			#if DIRECTION_GPIO_PORT_1_PIN_20 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_20, GPIO_TYPE_GPIO_PORT_1_PIN_20, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_20, DIRECTION_GPIO_PORT_1_PIN_20);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_20, GPIO_TYPE_GPIO_PORT_1_PIN_20, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_20 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_20);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_20);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_20, DIRECTION_GPIO_PORT_1_PIN_20);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_21
			#if DIRECTION_GPIO_PORT_1_PIN_21 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_21, GPIO_TYPE_GPIO_PORT_1_PIN_21, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_21, DIRECTION_GPIO_PORT_1_PIN_21);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_21, GPIO_TYPE_GPIO_PORT_1_PIN_21, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_21 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_21);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_21);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_21, DIRECTION_GPIO_PORT_1_PIN_21);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_22
			#if DIRECTION_GPIO_PORT_1_PIN_22 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_22, GPIO_TYPE_GPIO_PORT_1_PIN_22, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_22, DIRECTION_GPIO_PORT_1_PIN_22);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_22, GPIO_TYPE_GPIO_PORT_1_PIN_22, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_22 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_22);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_22);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_22, DIRECTION_GPIO_PORT_1_PIN_22);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_23
			#if DIRECTION_GPIO_PORT_1_PIN_23 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_23, GPIO_TYPE_GPIO_PORT_1_PIN_23, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_23, DIRECTION_GPIO_PORT_1_PIN_23);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_23, GPIO_TYPE_GPIO_PORT_1_PIN_23, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_23 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_23);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_23);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_23, DIRECTION_GPIO_PORT_1_PIN_23);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_24
			#if DIRECTION_GPIO_PORT_1_PIN_24 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_24, GPIO_TYPE_GPIO_PORT_1_PIN_24, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_24, DIRECTION_GPIO_PORT_1_PIN_24);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_24, GPIO_TYPE_GPIO_PORT_1_PIN_24, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_24 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_24);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_24);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_24, DIRECTION_GPIO_PORT_1_PIN_24);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_25
			#if DIRECTION_GPIO_PORT_1_PIN_25 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_25, GPIO_TYPE_GPIO_PORT_1_PIN_25, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_25, DIRECTION_GPIO_PORT_1_PIN_25);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_25, GPIO_TYPE_GPIO_PORT_1_PIN_25, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_25 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_25);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_25);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_25, DIRECTION_GPIO_PORT_1_PIN_25);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_26
			#if DIRECTION_GPIO_PORT_1_PIN_26 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_26, GPIO_TYPE_GPIO_PORT_1_PIN_26, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_26, DIRECTION_GPIO_PORT_1_PIN_26);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_26, GPIO_TYPE_GPIO_PORT_1_PIN_26, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_26 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_26);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_26);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_26, DIRECTION_GPIO_PORT_1_PIN_26);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_27
			#if DIRECTION_GPIO_PORT_1_PIN_27 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_27, GPIO_TYPE_GPIO_PORT_1_PIN_27, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_27, DIRECTION_GPIO_PORT_1_PIN_27);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_27, GPIO_TYPE_GPIO_PORT_1_PIN_27, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_27 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_27);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_27);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_27, DIRECTION_GPIO_PORT_1_PIN_27);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_28
			#if DIRECTION_GPIO_PORT_1_PIN_28 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_28, GPIO_TYPE_GPIO_PORT_1_PIN_28, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_28, DIRECTION_GPIO_PORT_1_PIN_28);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_28, GPIO_TYPE_GPIO_PORT_1_PIN_28, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_28 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_28);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_28);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_28, DIRECTION_GPIO_PORT_1_PIN_28);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_29
			#if DIRECTION_GPIO_PORT_1_PIN_29 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_29, GPIO_TYPE_GPIO_PORT_1_PIN_29, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_29, DIRECTION_GPIO_PORT_1_PIN_29);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_29, GPIO_TYPE_GPIO_PORT_1_PIN_29, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_29 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_29);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_29);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_29, DIRECTION_GPIO_PORT_1_PIN_29);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_30
			#if DIRECTION_GPIO_PORT_1_PIN_30 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_30, GPIO_TYPE_GPIO_PORT_1_PIN_30, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_30, DIRECTION_GPIO_PORT_1_PIN_30);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_30, GPIO_TYPE_GPIO_PORT_1_PIN_30, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_30 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_30);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_30);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_30, DIRECTION_GPIO_PORT_1_PIN_30);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_1_PIN_31
			#if DIRECTION_GPIO_PORT_1_PIN_31 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_31, GPIO_TYPE_GPIO_PORT_1_PIN_31, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_31, DIRECTION_GPIO_PORT_1_PIN_31);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_1_PIN_31, GPIO_TYPE_GPIO_PORT_1_PIN_31, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_1_PIN_31 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_1_PIN_31);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_1_PIN_31);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_1_PIN_31, DIRECTION_GPIO_PORT_1_PIN_31);
			#endif
		#endif
	#endif

	#if	ENABLE_GPIO_PORT2

		#if ENABLE_GPIO_PORT_2_PIN_0
				#if DIRECTION_GPIO_PORT_2_PIN_0 == 0
					Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_0, GPIO_TYPE_GPIO_PORT_2_PIN_0, IOCON_FUNC0);
					Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_0, DIRECTION_GPIO_PORT_2_PIN_0);
				#else
					Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_0, GPIO_TYPE_GPIO_PORT_2_PIN_0, IOCON_FUNC0);
					#if GPIO_TYPE_GPIO_PORT_2_PIN_0 == OD
						Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_0);
					#else
						Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_0);
					#endif
					Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_0, DIRECTION_GPIO_PORT_2_PIN_0);
				#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_1
			#if DIRECTION_GPIO_PORT_2_PIN_1 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_1, GPIO_TYPE_GPIO_PORT_2_PIN_1, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_1, DIRECTION_GPIO_PORT_2_PIN_1);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_1, GPIO_TYPE_GPIO_PORT_2_PIN_1, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_1 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_1);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_1);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_1, DIRECTION_GPIO_PORT_2_PIN_1);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_2
			#if DIRECTION_GPIO_PORT_2_PIN_2 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_2, GPIO_TYPE_GPIO_PORT_2_PIN_2, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_2, DIRECTION_GPIO_PORT_2_PIN_2);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_2, GPIO_TYPE_GPIO_PORT_2_PIN_2, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_2 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_2);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_2);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_2, DIRECTION_GPIO_PORT_2_PIN_2);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_3
			#if DIRECTION_GPIO_PORT_2_PIN_3 == 0
					Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_3, GPIO_TYPE_GPIO_PORT_2_PIN_3, IOCON_FUNC0);
					Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_3, DIRECTION_GPIO_PORT_2_PIN_3);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_3, GPIO_TYPE_GPIO_PORT_2_PIN_3, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_3 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_3);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_3);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_3, DIRECTION_GPIO_PORT_2_PIN_3);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_4
			#if DIRECTION_GPIO_PORT_2_PIN_4 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_4, GPIO_TYPE_GPIO_PORT_2_PIN_4, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_4, DIRECTION_GPIO_PORT_2_PIN_4);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_4, GPIO_TYPE_GPIO_PORT_2_PIN_4, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_4 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_4);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_4);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_4, DIRECTION_GPIO_PORT_2_PIN_4);
			#endif
		#endif


		#if ENABLE_GPIO_PORT_2_PIN_5
			#if DIRECTION_GPIO_PORT_2_PIN_5 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_5, GPIO_TYPE_GPIO_PORT_2_PIN_5, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_5, DIRECTION_GPIO_PORT_2_PIN_5);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_5, GPIO_TYPE_GPIO_PORT_2_PIN_5, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_5 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_5);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_5);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_5, DIRECTION_GPIO_PORT_2_PIN_5);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_6
			#if DIRECTION_GPIO_PORT_2_PIN_6 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_6, GPIO_TYPE_GPIO_PORT_2_PIN_6, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_6, DIRECTION_GPIO_PORT_2_PIN_6);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_6, GPIO_TYPE_GPIO_PORT_2_PIN_6, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_6 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_6);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_6);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_6, DIRECTION_GPIO_PORT_2_PIN_6);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_7
			#if DIRECTION_GPIO_PORT_2_PIN_7 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_7, GPIO_TYPE_GPIO_PORT_2_PIN_7, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_7, DIRECTION_GPIO_PORT_2_PIN_7);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_7, GPIO_TYPE_GPIO_PORT_2_PIN_7, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_7 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_7);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_7);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_7, DIRECTION_GPIO_PORT_2_PIN_7);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_8
			#if DIRECTION_GPIO_PORT_2_PIN_8 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_8, GPIO_TYPE_GPIO_PORT_2_PIN_8, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_8, DIRECTION_GPIO_PORT_2_PIN_8);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_8, GPIO_TYPE_GPIO_PORT_2_PIN_8, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_8 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_8);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_8);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_8, DIRECTION_GPIO_PORT_2_PIN_8);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_9
			#if DIRECTION_GPIO_PORT_2_PIN_9 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_9, GPIO_TYPE_GPIO_PORT_2_PIN_9, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_9, DIRECTION_GPIO_PORT_2_PIN_9);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_9, GPIO_TYPE_GPIO_PORT_2_PIN_9, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_9 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_9);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_9);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_9, DIRECTION_GPIO_PORT_2_PIN_9);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_10
			#if DIRECTION_GPIO_PORT_2_PIN_10 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_10, GPIO_TYPE_GPIO_PORT_2_PIN_10, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_10, DIRECTION_GPIO_PORT_2_PIN_10);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_10, GPIO_TYPE_GPIO_PORT_2_PIN_10, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_10 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_10);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_10);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_10, DIRECTION_GPIO_PORT_2_PIN_10);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_11
			#if DIRECTION_GPIO_PORT_2_PIN_11 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_11, GPIO_TYPE_GPIO_PORT_2_PIN_11, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_11, DIRECTION_GPIO_PORT_2_PIN_11);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_11, GPIO_TYPE_GPIO_PORT_2_PIN_11, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_11 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_11);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_11);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_11, DIRECTION_GPIO_PORT_2_PIN_11);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_12
			#if DIRECTION_GPIO_PORT_2_PIN_12 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_12, GPIO_TYPE_GPIO_PORT_2_PIN_12, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_12, DIRECTION_GPIO_PORT_2_PIN_12);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_12, GPIO_TYPE_GPIO_PORT_2_PIN_12, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_12 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_12);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_12);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_12, DIRECTION_GPIO_PORT_2_PIN_12);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_2_PIN_13
			#if DIRECTION_GPIO_PORT_2_PIN_13 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_13, GPIO_TYPE_GPIO_PORT_2_PIN_13, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_13, DIRECTION_GPIO_PORT_2_PIN_13);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_2_PIN_13, GPIO_TYPE_GPIO_PORT_2_PIN_13, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_2_PIN_13 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_2_PIN_13);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_2_PIN_13);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_2_PIN_13, DIRECTION_GPIO_PORT_2_PIN_13);
			#endif
		#endif
	#endif

	#if	ENABLE_GPIO_PORT3
		#if ENABLE_GPIO_PORT_3_PIN_25
			#if DIRECTION_GPIO_PORT_3_PIN_25 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_3_PIN_25, GPIO_TYPE_GPIO_PORT_3_PIN_25, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_3_PIN_25, DIRECTION_GPIO_PORT_3_PIN_25);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_3_PIN_25, GPIO_TYPE_GPIO_PORT_3_PIN_25, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_3_PIN_25 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_3_PIN_25);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_3_PIN_25);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_3_PIN_25, DIRECTION_GPIO_PORT_3_PIN_25);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_3_PIN_26
			#if DIRECTION_GPIO_PORT_3_PIN_26 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_3_PIN_26, GPIO_TYPE_GPIO_PORT_3_PIN_26, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_3_PIN_26, DIRECTION_GPIO_PORT_3_PIN_26);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_3_PIN_26, GPIO_TYPE_GPIO_PORT_3_PIN_26, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_3_PIN_26 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_3_PIN_26);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_3_PIN_26);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_3_PIN_26, DIRECTION_GPIO_PORT_3_PIN_26);
			#endif
		#endif
	#endif

	#if	ENABLE_GPIO_PORT4
		#if ENABLE_GPIO_PORT_4_PIN_28
			#if DIRECTION_GPIO_PORT_4_PIN_28 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_4_PIN_28, GPIO_TYPE_GPIO_PORT_4_PIN_28, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_4_PIN_28, DIRECTION_GPIO_PORT_4_PIN_28);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_4_PIN_28, GPIO_TYPE_GPIO_PORT_4_PIN_28, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_4_PIN_28 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_4_PIN_28);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_4_PIN_28);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_4_PIN_28, DIRECTION_GPIO_PORT_4_PIN_28);
			#endif
		#endif

		#if ENABLE_GPIO_PORT_4_PIN_29
			#if DIRECTION_GPIO_PORT_4_PIN_29 == 0
				Chip_IOCON_PinMux(LPC_IOCON,PORT_4_PIN_29, GPIO_TYPE_GPIO_PORT_4_PIN_29, IOCON_FUNC0);
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_4_PIN_29, DIRECTION_GPIO_PORT_4_PIN_29);
			#else
				Chip_IOCON_PinMux(LPC_IOCON,PORT_4_PIN_29, GPIO_TYPE_GPIO_PORT_4_PIN_29, IOCON_FUNC0);
				#if GPIO_TYPE_GPIO_PORT_4_PIN_29 == OD
					Chip_IOCON_EnableOD(LPC_IOCON, PORT_4_PIN_29);
				#else
					Chip_IOCON_DisableOD(LPC_IOCON, PORT_4_PIN_29);
				#endif
				Chip_GPIO_SetPinDIR(LPC_GPIO,PORT_4_PIN_29, DIRECTION_GPIO_PORT_4_PIN_29);
			#endif
		#endif
	#endif
#endif
}

/************************************************************************************/
/*										S A T O R									*/
/*										A R E P O									*/
/*										T E N E T									*/
/*										O P E R A									*/
/*										R O T A S									*/
/************************************************************************************/
